name = "meeting-time-api"
main = "src/index.ts"
compatibility_date = "2025-01-01"

[[d1_databases]]
binding = "DB"
database_name = "meeting-time-db"
# Nahraď tímto ID po spuštění: wrangler d1 create meeting-time-db
database_id = "6c7c87de-7d5b-4035-903d-2f61b64fe70b"
